services:
  - type: web
    name: confluence-ai-assistant
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GENAI_API_KEY_1
        sync: false
      - key: CONFLUENCE_BASE_URL
        sync: false
      - key: CONFLUENCE_USER_EMAIL
        sync: false
      - key: CONFLUENCE_API_KEY
        sync: false 